### ISSUE TITLE
About Pre-trained Wikipedia embeddings

### ISSUE THREAD

**Issue by states786** [4OH4/doc-similarity#3]
Hi,

Can you please confirm the specification of by-default pre-trained Wikipedia embeddings used in GLOVE?
Is it like Wikipedia (2014, Gigaword 5, vector dimension 50)?

**Comment by 4OH4** [comment]
Yes - the default GloVe model used in the DocSim class is 'glove-wiki-gigaword-50' from Gensim. More details here: https://github.com/RaRe-Technologies/gensim-data
